spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 123456
  web:
    resources:
      static-locations: classpath:/static/,file:/static/
server:
  port: 8080
mybatis:
  type-aliases-package:  zjitc.zrt.blogspb.domain
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
